name: smib
services:
  smib:
    container_name: smib
    hostname: smib
    image: smib
    build: ${SMIB_BUILD_GIT_TAG:+https://github.com/somakeit/smib.git#}${SMIB_BUILD_GIT_TAG:-.}
    env_file: .env
    environment:
      MONGO_DB_HOST: ${MONGO_DB_HOST:-smib-db}
    depends_on:
      - smib-db
    ports:
      - "${SMIB_WEBSERVER_EXTERNAL_PORT:-80}:${SMIB_WEBSERVER_INTERNAL_PORT:-80}"
    restart: unless-stopped

  smib-db:
    image: mongo:${MONGO_DB_TAG:-latest}
    container_name: smib-db
    env_file: .env
    restart: unless-stopped

  smib-db-ui:
    image: mongo-express
    container_name: smib-db-ui
    depends_on:
      - smib-db
    env_file: .env
    environment:
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL:-mongodb://smib-db:27017/}
    ports:
      - "${MONGO_DB_UI_PORT:-8081}:8081"
    restart: unless-stopped

networks:
  default:
    name: smib-bridge-network
    driver: bridge
